spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
  properties:
    hibernate:
      hbm2ddl:
        show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
        org.hibernate.SQL: DEBUG        # mostra o SQL gerado
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # mostra os valores dos parâmetros
        org.hibernate.tool.hbm2ddl: DEBUG